version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_test_db
      POSTGRES_USER: serhiiravliuk
      POSTGRES_PASSWORD: kabosina2517
    networks:
      - mynetwork

  app:
    build: .
    environment:
      DATABASE_URL: postgres://serhiiravliuk:kabosina2517@postgres/my_test_db
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:

