pipeline {
    agent any

    environment {
        BASE_URL = '/Users/serhii.ravliuk/PycharmProjects/Lesson_2_1/lesson_28'
        REQUIREMENTS_FILE = "${BASE_URL}/requirements.txt"
        PYTHON_VERSION = '3.11.9'
        VENV_DIR = '.venv'
        REPO_URL = 'https://github.com/SerhiiRavliuk/Lesson_2.git'
        TEST_DIR = "${BASE_URL}/tests/test_automation.py"
        ALLURE_REPORT_PATH = "${BASE_URL}/allure-report"
        ALLURE_RESULTS_PATH = "${BASE_URL}/allure-results"

    }

    stages {
        stage('Checkout Code from GitHub') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Install Python and Create Virtual Environment') {
            steps {
                script {
                    sh """
                        # Install pyenv if not already installed
                        if [ ! -d "\$HOME/.pyenv" ]; then
                            echo "Installing pyenv..."
                            curl https://pyenv.run | bash
                        else
                            echo "pyenv already installed."
                        fi

                        # Add pyenv to the PATH
                        export PATH="\$HOME/.pyenv/bin:\$PATH"
                        eval "\$(pyenv init --path)"
                        eval "\$(pyenv init -)"

                        # Install specified Python version
                        pyenv install -s ${PYTHON_VERSION}
                        pyenv global ${PYTHON_VERSION}

                        # Create virtual environment if it doesn't exist
                        if [ ! -d "${VENV_DIR}" ]; then
                            echo "Creating virtual environment..."
                            python3 -m venv ${VENV_DIR}
                        else
                            echo "Virtual environment already exists."
                        fi
                    """
                }
            }
        }

        stage('Activate Virtual Environment and Install Dependencies') {
            steps {
                script {
                    sh """
                        # Activate virtual environment
                        source ${VENV_DIR}/bin/activate

                        # Update pip and install dependencies
                        pip install --upgrade pip
                        pip install -r ${REQUIREMENTS_FILE}
                        pip install allure-pytest  # Install Allure for pytest
                    """
                }
            }
        }

        stage('Run Tests and Generate Allure Results') {
            steps {
                script {
                    sh """
                        # Run the tests with pytest and generate allure results
                        source ${VENV_DIR}/bin/activate
                        pytest ${TEST_DIR} --maxfail=1 --disable-warnings -q --alluredir=${ALLURE_RESULTS_PATH}
                    """
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                script {
                    sh """
                        # Generate Allure report
                        allure generate ${ALLURE_RESULTS_PATH} --clean -o ${ALLURE_REPORT_PATH}
                    """
                }
            }
        }

        stage('Publish Allure Report') {
            steps {
                allure([
                    includeProperties: false,
                    jdk: '',
                    report: "${ALLURE_REPORT_PATH}",
                    results: "${ALLURE_RESULTS_PATH}"
                ])
            }
        }

        // Автоматичне відкривання Allure звіту на сервері:
        stage('Serve Allure Report Locally') {
            steps {
                script {
                    sh """
                        # Serve the Allure report locally
                        allure serve ${ALLURE_REPORT_PATH}

                    """
                }
            }
        }
    }

    post {
        always {
            script {
                email text(
                    subject: "Test Results for ${currentBuild.fullDisplayName}",
                    body: "Please find the test results attached for ${currentBuild.fullDisplayName}.",
                    to: "serhii.ravliuk@gmail.com"
                )
            }
        }
    }
}
