css_locator_1: str = "div[class = 'logo pull-left']>a>img"
css_locator_2: str = "li>a>i[class='fa fa-home']"
css_locator_3: str = "a[href='/products']"
css_locator_4: str = "a[href='/login']"
css_locator_5: str = "section[id='slider']"
css_locator_6: str = "a[href='#Women']"
css_locator_8: str = "a[href='#Men']"
css_locator_9: str = "a[href='/brand_products/Polo']"
css_locator_10: str = "a[href='/brand_products/H&M']"
css_locator_11: str = "img[src$='13']"
css_locator_12: str = "img[src$='19']"
css_locator_13: str = "a[href='/products']>u"
css_locator_14: str = "input[id$='email']"
css_locator_15: str = "button[id='subscribe']"
css_locator_16: str = "a[href$='#collapse1']"
css_locator_18: str = "a[href$='#collapse4']"
css_locator_19: str = "a[href$='/api_list']"
css_locator_20: str = "h4>a[href$='#collapse1']"
css_locator_21: str = "h2>b"
css_locator_22: str = "li.list-group-item>b"




xpath_locator_1: str = ".//li[contains(@class, 'list-group-item')]/a[@href = 'https://automationexercise.com/api/productsList']"
xpath_locator_2: str = "(//li[contains(@class, 'list-group-item')]/a[@href='https://automationexercise.com/api/productsList'])[1]"
xpath_locator_3: str = "(//a[@href='https://automationexercise.com/api/brandsList'])[2]"
xpath_locator_4: str = "(//img[contains(@class, 'yt-core-image')])[2]"
xpath_locator_5: str = "(//div[contains(@class, 'shape__fill')])[6]"
xpath_locator_6: str = "(//a[contains(@id, 'endpoint')and @title='Головна'])[2]"
xpath_locator_7: str = ".//button[@id='ember10']"
xpath_locator_8: str = ".//a[@href='#/admin']"
xpath_locator_9: str = ".//input[@placeholder='Member Search']"
xpath_locator_10: str = ".//div[@class='user-menu-trigger']"
xpath_locator_11: str = "(.//div[@class='cell-wrap'])[2]"
xpath_locator_12: str = ".//input[@placeholder='Pick a date']"
xpath_locator_13: str = ".//input[@class='search']"
xpath_locator_14: str = ".//div[cotains(@class, 'fixed-size')]"
xpath_locator_15: str = ".//a[@title='Employers']"
xpath_locator_16: str = ".//a[@id='ember1127']"
xpath_locator_17: str = ".//a[@id='ember1156']"
xpath_locator_18: str = ".//a[@href='#/admin/users/new']"
xpath_locator_19: str = "(.//button[contains(@class, 'compact basic')])[1]"
xpath_locator_20: str = ".//input[@placeholder='Search...']"
xpath_locator_21: str = ".//input[@id='ember1641']"
xpath_locator_22: str = "(.//div/span[@class='cell-text'])[3]"
xpath_locator_23: str = ".//a[contains(@class, 'icon button ui')]"
xpath_locator_24: str = ".//a[contains(@href, '14012')]"
xpath_locator_25: str = ".//a[@href = '#/services/flows/14012']"
xpath_locator_26: str = "(.//a[@href = '#'])[1]"
xpath_locator_27: str = "(.//a[@class='ui button seconday'])[1]"
xpath_locator_28: str = "(.//a[@title='Download'])[1]"
xpath_locator_29: str = "(.//div[contains(@class, 'ui label red basic')])[1]"
xpath_locator_30: str = ".//div[@id='ember2439']"
xpath_locator_31: str = ".//button[@id='ember2847']"
xpath_locator_32: str = ".//button[@id='ember3091']"
xpath_locator_33: str = ".//div[contains(@class,'ui pop')]"
xpath_locator_34: str = ".//div[contains(@title ,'Invoice Name')]"
xpath_locator_35: str = "(.//span[contains(@class ,'action-sort')])[1]"
xpath_locator_36: str = "(.//button[contains(@id ,'ember885')])"
xpath_locator_37: str = ".//input[@name='fromDate' and @id='ember1739']"
xpath_locator_38: str = ".//div[@id='ember1749']"